apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
  - image: derorisan/ununifi-proposal-atomfeed
    docker:
      dockerfile: ./Dockerfile
  local:
    push: true
    useBuildkit: true
deploy:
  kubectl:
    manifests:
    - ./k8s.yaml
